### ISSUE TITLE
DB Error #1021 - notifications from Docker Image

### ISSUE THREAD

**Issue by kvn95ss** [tiredofit/docker-osticket#23]
Hello,

I managed to host osticket in docker, and test it with a few users.

Today, I noticed that the docker service was running very slow, and I started receiving these notifications from the docker image - 

```
[SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'ost_queue' AND TABLE_SCHEMA = DATABASE() ORDER BY ORDINAL_POSITION]

Disk full (/tmp/#sql-temptable-23b-e-c.MAI); waiting for someone to free some space... (errno: 28 "No space left on device")<br />
<br />
---- Backtrace ----<br />
#0 (root)/include/mysqli.php(201): osTicket->logDBError('DB Error #1021', '[SELECT COLUMN_...')<br />
#1 (root)/include/class.orm.php(3466): db_query('SELECT COLUMN_N...', true, true)<br />
#2 (root)/include/class.orm.php(3522): MySqlExecutor->execute()<br />
#3 (root)/include/class.orm.php(3265): MySqlExecutor->getRow()<br />
#4 (root)/include/class.orm.php(292): MySqlCompiler->inspectTable('ost_queue')<br />
#5 (root)/include/class.orm.php(255): ModelMeta->inspectFields()<br />
#6 (root)/include/class.orm.php(3017): ModelMeta->getFieldNames()<br />
#7 (root)/include/class.orm.php(1632): MySqlCompiler->compileSelect(Object(QuerySet))<br />
#8 (root)/include/class.orm.php(1844): QuerySet->getQuery()<br />
#9 (root)/include/class.orm.php(1567): ModelInstanceManager->__construct(Object(QuerySet))<br />
#10 (root)/include/class.orm.php(1555): QuerySet->getIterator()<br />
#11 (root)/include/class.queue.php(1447): QuerySet->__call('asArray', Array)<br />
#12 (root)/scp/tickets.php(29): CustomQueue::getHierarchicalQueues(Object(StaffSession))<br />
```

I'm getting this notification constantly. I have edited the docker-compose.yml to mount another directory as temp storage, to be precise the following changes were made 
```
    volumes:
      - ./data/:/www/osticket
      - ./logs/:/www/logs
      - ./tmp:/tmp # My addition
```
But it doesn't seem to be helping with the error messages. The tmp directory has two folders inside it as well

```
tmp
├── nginx
└── state
    ├── 00-startup-init
    ├── 01-timezone-init
    ├── 02-permissions-init
    ├── 03-monitoring
    ├── 03-monitoring-init
    ├── 04-scheduling
    ├── 04-scheduling-init
    ├── 05-logging-init
    ├── 06-messaging-init
    ├── 10-nginx
    ├── 10-nginx-init
    ├── 11-nginx-config-reload-init
    ├── 20-php-fpm
    ├── 20-php-fpm-init
    ├── 30-osticket-init
    ├── 99-container-init
    └── cron
        └── 1672725677
```

Now I'm getting a 503 ngix bad gateway error. I'm stumped, any help will be appreciated!

**Comment by miguelwill** [comment]
> Disk full (/tmp/#sql-temptable-23b-e-c.MAI); waiting for someone to free some space... (errno: 28 "No space left on device")


check system free space
